mode: auto

#å¤´åƒ
avatar:
  enable: true
  url: https://s2.loli.net/2022/05/31/U5JQfLTbqk3Cv9P.jpg
  rounded: true
  opacity: 1
  mickey_mouse: false
  status:
    enable: true
    emoji: ğŸŒˆ
    message: ç«¯åˆå®‰åº·ï¼

reward:
  enable: true
  comment: è¯·ä¸è¦ç»™æˆ‘æ‰“é’±ï¼Œæˆ‘å¯ä¸ä¼šè¿˜ç»™ä½ å‘¦
  methods:
    - name: æ”¯ä»˜å®
      path: https://s2.loli.net/2022/06/03/tCqIUTsexGL63ok.jpg
      color: '#00A3EE'
      icon: ri:alipay-line
    - name: QQ æ”¯ä»˜
      path: https://s2.loli.net/2022/06/03/eKinQN4z9RqgrYy.png
      color: '#12B7F5'
      icon: ri:qq-line
    - name: å¾®ä¿¡æ”¯ä»˜
      path: https://s2.loli.net/2022/06/03/gMshOJ4fbkDGETX.png
      color: '#2DC100'
      icon: ri:wechat-pay-line

comment:
  candidates:
    - waline
    # - giscus
  tips:
    - å¦‚æœæ‚¨æœ‰ä»»ä½•å…³äºåšå®¢å†…å®¹çš„ç›¸å…³è®¨è®ºï¼Œæ¬¢è¿å‰å¾€ <a href="https://github.com/YunYouJun/yunyoujun.github.io/discussions" target="_blank">GitHub Discussions</a> ä¸æˆ‘äº¤æµã€‚

waline:
  enable: false
  serverURL: https://waline.yunyoujun.cn
  visitor: true
  comment: true
  emoji:
    - https://fastly.jsdelivr.net/gh/walinejs/emojis@latest/bilibili/
    - https://fastly.jsdelivr.net/gh/walinejs/emojis@latest/weibo/
    - https://fastly.jsdelivr.net/gh/walinejs/emojis@latest/qq/
  locale:
    placeholder: å¡«å†™é‚®ç®±ï¼Œå¯ä»¥æ”¶åˆ°å›å¤é€šçŸ¥å“¦ï½  (å»ºè®®ä½¿ç”¨QQé‚®ç®±)
  requiredMeta: [nick]

github_issues:
  enable: false

github_discussions:
  enable: false

disqusjs:
  enable: false
  shortname: yunyoujun
  apikey: ouoGQCaamOKdJgyZU5DKcpFnRIg3SNzvk0nwygPtlcTRJuE68c8igvrZGW4wAJoN

# https://github.com/laymonage/giscus
giscus:
  enable: false
  repo: YunYouJun/yunyoujun.github.io
  repo-id:
  category-id:
  mapping: pathname
  reactions-enabled: 1
  emit-metadata: 0
  theme: light

footer:
  since: 2022
  icon:
    url: 
    title: æŸ¯å°”é¸­çš„èµåŠ©è€…ä»¬
  beian:
    enable: false
    icp: è‹ICPå¤‡17038157å·
  live_time:
    enable: true
    prefix: æœ¬åšå®¢å·²èŒèŒå“’åœ°è¿è¡Œäº†
    suffix: (â—'â—¡'â—)
    start_time: '2022-05-31T13:14:00'
  support:
    enable: false
    title: åˆæ‹äº‘
    link: https://www.upyun.com
    logo: https://cdn.yunyoujun.cn/img/logo/upyun-logo.png
    prefix: æœ¬ç½‘ç«™ç”±
    suffix: æä¾› CDN åŠ é€Ÿ
  custom_text:


engine_search:
  enable: false

# If you want to use it, you need config algolia appID in _config.yml!!!
# https://github.com/oncletom/hexo-algolia
algolia_search:
  enable: false
  # ...

google_analytics:
  enable: true
  id: G-1LL0D86CY9

google_adsense:
  enable: true
  client: ca-pub-2245427233262012

post_edit:
  enable: true
  url: https://github.com/YunYouJun/yunyoujun.github.io/tree/hexo/source/

albums:
  enable: true

girls:
  enable: true

#UI
banner:
  enable: true
  title: å¾ˆé«˜å…´é‡è§ä½ 
  border: true
  cloud:
    enable: true
    color: white
  go_down:
    enable: true
    icon: ri:arrow-down-s-line

wordcloud:
  enable: true

categories:
  æ‚é¡¹: 'CCFFFF'

#cdn:
  #pre: https://cdn.jsdelivr.net/gh/yzikey/yzikey.github.io@latest


pages:
  - name: æˆ‘çš„å°ä¼™ä¼´ä»¬
    url: /links/
    icon: ph:address-book
    color: dodgerblue
  - name: å–œæ¬¢çš„åŠ¨æ¼«è§’è‰²
    url: /girls/
    icon: ph:heart-duotone
    color: pink
  - name: ç›¸å†Œé›†
    url: /albums/
    icon: ph:camera-bold
    color: dimgray
    theme: wave
    password: hello

menu:
  custom:
    title: ç•™è¨€æ¿
    path: /about/comment
    icon: ri:clipboard-line
  home:
    path: /
    icon: ri:home-4-line
  list:
    - type: archives
      path: /archives/
      icon: ri:archive-line
    - type: categories
      path: /categories/
      icon: ri:folder-2-line
    - type: tags
      path: /tags/
      icon: ri:price-tag-3-line


cursor:
  enable: true

baidu_push: true

google_tagmanager:
  enable: true
  id: GTM-M9KWR9L

wordcount:
  enable: false

say:
  enable: true
  api: /data/sentences.json
  hitokoto:
    enable: false

mourn:
  enable: true
  days:
    - 4-4

pjax:
  enable: true

aplayer:
  global: true
  meting: true
  # https://github.com/metowolf/MetingJS/tree/v1.2#option
  widget:
    enable: true
    #id: 1364247901
    autoplay: true
    theme: '#2980b9'
    loop: all
    order: random
    preload: auto
    volume: 0.7
    mutex: true
    lrcType: 0
    listFolded: false
    listMaxHeight: 340px
    meting:
      enable: true
      id: 7466748299
      server: netease
      type: playlist

social:
#  - name: RSS
    # set rss in your root config
    # https://github.com/hexojs/hexo-generator-feed
#    link: /atom.xml # config.feed.path
#    icon: ri:rss-line
#    color: orange
  - name: GitHub
    link: https://github.com/yzikey
    icon: ri:github-line
    color: '#6e5494'
  - name: å¾®åš
    link: https://weibo.com/u/7273500676
    icon: ri:weibo-line
    color: '#E6162D'
  - name: ç½‘æ˜“äº‘éŸ³ä¹
    link: https://music.163.com/#/user/home?id=1761720689
    icon: ri:netease-cloud-music-line
    color: '#C20C0C'
  - name: çŸ¥ä¹
    link: https://www.zhihu.com/people/du-zhu-23-39-93
    icon: ri:zhihu-line
    color: '#0084FF'
  - name: å“”å“©å“”å“©
    link: https://space.bilibili.com/12848975
    icon: ri:bilibili-line
    color: '#FF8EB3'
#  - name: å¾®ä¿¡å…¬ä¼—å·
#    link: https://cdn.yunyoujun.cn/img/about/white-qrcode-and-search.jpg
#    icon: ri:wechat-2-line
#    color: '#1AAD19'
#  - name: E-Mail
#    link: mailto:me@yunyoujun.cn
#    icon: ri:mail-line
#    color: '#8E71C1'

# pjax:
#   enable: true